

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'
    
steps:
  - task: Docker@2
    displayName: Build Api image
    inputs:
      repository: youtubedlk-aas-api
      command: build
      Dockerfile: api/Dockerfile
  - task: Docker@2
    displayName: Build Web app image
    inputs:
      repository: youtubedlk-aas-app
      command: build
      Dockerfile: app/Dockerfile