version: '3'
services: 
  api:
    build: ./api
    ports:
      - "8000"
  app:
    build: ./app
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=$APP_DOMAIN
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=$APP_DOMAIN
      - LETSENCRYPT_EMAIL=$APP_MAIL
    volumes:
      - /home/olex/static/files:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: nginx-proxy
