#!/bin/bash
# docker-compose down
# docker-compose up -d
docker build -t docker-youtubedl-aas-tests $(dirname "$0")/../api
podman-compose -f $(dirname "$0")/docker-compose.yml down
podman-compose -f $(dirname "$0")/docker-compose.yml up -d
pytest -q -s
# docker-compose down
podman-compose -f $(dirname "$0")/docker-compose.yml down
